# Oracle Database Free 23.5 base image
# Note: Oracle Enterprise images (oracle/database-enterprise:* ) are NOT publicly pullable.
# Oracle Database Free is anonymous-pullable from container-registry.oracle.com.
FROM container-registry.oracle.com/database/free:23.5.0.0