name: Build & Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Build & Push all images
        run: ./build.sh
        env:
          REGISTRY: ghcr.io
          NAMESPACE: prasanth595
